In [63]:
import numpy as np

## Транспонирование матрицы

Свойство 1. Дважды транспонированная матрица равна исходной матрице.

In [64]:
A = np.matrix('3 6 5; 9 8 1')
t_matrix = (A.T).T
print(t_matrix)

[[3 6 5]
 [9 8 1]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц

In [65]:
A = np.matrix('2 3 6; 3 9 1')
B = np.matrix('4 3 5; 9 8 0')
first = (A + B).T
second = A.T + B.T
print(first)
print(second)

[[ 6 12]
 [ 6 17]
 [11  1]]
[[ 6 12]
 [ 6 17]
 [11  1]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [66]:
A = np.matrix('5 6 8; 1 2 6')
B = np.matrix('2 2; 3 5; 6 7')
first = (A.dot(B)).T
second = (B.T).dot(A.T)
print(first)
print(second)

[[76 44]
 [96 54]]
[[76 44]
 [96 54]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [67]:
A = np.matrix('5 8 9; 1 3 8')
k = 5
first = k * (A.T)
second = (k * A).T
print(first)
print(second)

[[25  5]
 [40 15]
 [45 40]]
[[25  5]
 [40 15]
 [45 40]]


*Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [68]:
A = np.matrix('2 4 3; 5 4 5; 5 5 5')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

5
5


# Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [69]:
A = np.matrix('2 2; 7 8')
L = 1 * A
R = A
print(L)
print(R)

[[2 2]
 [7 8]]
[[2 2]
 [7 8]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [70]:
A = np.matrix('8 8; 5 9')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [71]:
A = np.matrix('9 9; 3 5')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[45 45]
 [15 25]]
[[45 45]
 [15 25]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [72]:
A = np.matrix('7 6; 5 4')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[42 36]
 [30 24]]
[[42 36]
 [30 24]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [73]:
A = np.matrix('3 6; 0 1')
B = np.matrix('9 3; 6 7')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[36 27]
 [18 24]]
[[36 27]
 [18 24]]


# Сложение матриц

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [74]:
A = np.matrix('8 7; 8 7')
B = np.matrix('1 2; 2 9')
L = A + B
R = B + A
print(L)
print(R)

[[ 9  9]
 [10 16]]
[[ 9  9]
 [10 16]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [75]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей:

In [76]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)

[[0 0]
 [0 0]]


# Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [77]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [78]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [79]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)
print(R)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [80]:
A = np.matrix('1 2; 3 4')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)
print(R)
print(A)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [81]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)
print(R)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


# Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [82]:
A = np.matrix('-3 -2 0; 7 5 -2; 6 7 8')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-3 -2  0]
 [ 7  5 -2]
 [ 6  7  8]]
[[-3  7  6]
 [-2  5  7]
 [ 0 -2  8]]
-26.0
-26.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [83]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


0.0

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [84]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


14.0

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [85]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)
np.linalg.det(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


0.0

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [86]:
A = np.matrix('-7 -9 1; 1 2 -5; 6 3 7')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k
det_B

[[-7 -9  1]
 [ 1  2 -5]
 [ 6  3  7]]
[[-7 -9  1]
 [ 1  2 -5]
 [12  6 14]]


242.0

Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [87]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)
print(A)
print(B)
round(np.linalg.det(C), 3)
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


4.0

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [88]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


-14.0

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [89]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


0.0

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [90]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
k = 2
A[1, :] = k * A[0, :]
print(A)
round(np.linalg.det(A), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


0.0

# Обратная матрица

In [91]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [92]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]
[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [93]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
