## Матричный метод решения СЛАУ

Пусть дана система линейных уравнений с n неизвестными:
$$
\begin{align}
\begin{cases}
\\ a_1_1x_1 + ... +  a_1_nx_n = b_1;
\\ ................
\\  a_n_1x_1 + ... +  a_n_nx_n = b_n;
\end{cases}
\end{align}
$$
Её можно переписать в матричной форме: AX = B, где A — основная матрица системы, B и X — столбцы свободных членов и решений системы соответственно:
$$ A = \begin{pmatrix} a_1_1 & a_1_2 & ... & a_1_n \\ a_2_1 & a_2_2 & ... & a_2_n \\ ... & ... & ... & ... \\ a_n_1 & a_n_2 & ... & a_n_n \end{pmatrix}$$
$$ B = \begin{pmatrix} b_1 \\ b_2 \\ ... \\ b_n \end{pmatrix}$$
$$ X= \begin{pmatrix} x_1 \\ x_2 \\ ... \\ x_n \end{pmatrix}$$

Умножим это матричное уравнение слева на A-1 — матрицу, обратную к матрице A:  A-1 (AX) = A-1 B

Так как A-1A = E, получаем X = A-1B. Правая часть этого уравнения даст столбец решений исходной системы. Условием применимости данного метода (как и вообще существования решения неоднородной системы линейных уравнений с числом уравнений, равным числу неизвестных) является невырожденность матрицы A. Необходимым и достаточным условием этого является неравенство нулю определителя матрицы A: detA≠ 0.

Пример решения неоднородной системы линейных алгебраических уравнений:
$$
\begin{align}
\begin{cases}
\\ 3x + 2y -  z = 4;
\\ 2x -  y + 5z = 23;
\\  x + 7y -  z = 5;
\end{cases}
\end{align}
$$

$$ A = \begin{pmatrix} 2 & 3 & -1 \\ 2 & -1 & 5 \\ 1 & 7 &  -1 \end{pmatrix}$$
$$ B = \begin{pmatrix} 4 \\ 23 \\ 5 \end{pmatrix}$$
$$ X= \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix}$$

Убедимся в том, что определитель матрицы, составленный из коэффициентов при неизвестных системы линейных алгебраических уравнений не равен нулю.


In [130]:
import numpy as np
A = np.matrix('3 2 -1; 2 -1 5; 1 7 -1')
B = np.matrix('4; 23; 5')
print("Определитель матрицы: ",np.linalg.det(A))

Определитель матрицы:  -103.00000000000001


Найдем обратную матрицу:

In [131]:
A_inv = np.linalg.inv(A)
print("Обратная матрица: ")
print(A_inv)

Обратная матрица: 
[[ 0.33009709  0.04854369 -0.08737864]
 [-0.06796117  0.01941748  0.16504854]
 [-0.14563107  0.18446602  0.06796117]]


Найдем неизвестные. Для этого перемножим обратную матрицу  и столбец свободных членов.

In [132]:
X = A_inv.dot(B)
print("Решение системы: ")
print(X)

Решение системы: 
[[2.]
 [1.]
 [4.]]


## Метод Крамера решения СЛАУ

Пусть дана система линейных уравнений с n неизвестными:
$$
\begin{align}
\begin{cases}
\\ a_1_1x_1 + ... +  a_1_nx_n = b_1;
\\ ................
\\  a_n_1x_1 + ... +  a_n_nx_n = b_n;
\end{cases}
\end{align}
$$
Шаг 1. Вычисляем главный определитель матрицы:
$$
△ = \begin{pmatrix} a_1_1 & a_1_2 & ... & a_1_n \\ a_2_1 & a_2_2 & ... & a_2_n \\ ... & ... & ... & ... \\ a_n_1 & a_n_2 & ... & a_n_n \end{pmatrix}
$$
Шаг 2. Находим определители
$$
△x = \begin{pmatrix} b_1 & a_1_2 & ... & a_1_n \\ b_2 & a_2_2 & ... & a_2_n \\ ... & ... & ... & ... \\ b_n & a_n_2 & ... & a_n_n \end{pmatrix}
$$
$$
△y = \begin{pmatrix} a_1_1 & b_1 & ... & a_1_n \\ a_2_1 & b_2 & ... & a_2_n \\ ... & ... & ... & ... \\ a_n_1 & b_3 & ... & a_n_n \end{pmatrix}
$$
$$
△z = \begin{pmatrix} a_1_1 & a_1_2 & ... & b_1 \\ a_2_1 & a_2_2 & ... & n_2 \\ ... & ... & ... & ... \\ a_n_1 & a_n_2 & ... & b_n \end{pmatrix}
$$
Это определители матриц, которые получаются из матрицы A при замене столбцов на свободные члены.

Шаг 3. Вычисляем неизвестные переменные
Формулы Крамера, по которым вычисляем корни (неизвестные переменные):
$$
\begin{align}
x = \frac{△x}{△},  y = \frac{△y}{△},   z = \frac{△z}{△}
\end{align}
$$

Пример решения неоднородной системы линейных алгебраических уравнений:
$$
\begin{align}
\begin{cases}
\\ 3x + 2y -  z = 4;
\\ 2x -  y + 5z = 23;
\\  x + 7y -  z = 5;
\end{cases}
\end{align}
$$

Шаг 1. Вычисляем главный определитель матрицы:

In [133]:
print("Основная матрица: ")
print(A)
det_A = round(np.linalg.det(A),0)
print("Определитель основной матрицы: ", det_A)

Основная матрица: 
[[ 3  2 -1]
 [ 2 -1  5]
 [ 1  7 -1]]
Определитель основной матрицы:  -103.0


Шаг 2. Находим определители
Шаг 3. Вычисляем неизвестные переменные

In [134]:
k = 0 # счетчик
res = []
while k < len(A):
    A_temp = A.copy() # копируем изначальный массив
    A_temp[0:,k] = B # меняем в основной матрице столбец
    print(f"Матрица A при замене {k+1}го столбца на свободные члены: ")
    print(A_temp)
    det_temp = round(np.linalg.det(A_temp))
    print("Определитель: ",det_temp)
    A_res = det_temp/det_A
    print("Неизвестная переменная: ",A_res)
    res.append(A_res)
    k += 1
print("_______________________")
print("Ответ: ",res)

Матрица A при замене 1го столбца на свободные члены: 
[[ 4  2 -1]
 [23 -1  5]
 [ 5  7 -1]]
Определитель:  -206
Неизвестная переменная:  2.0
Матрица A при замене 2го столбца на свободные члены: 
[[ 3  4 -1]
 [ 2 23  5]
 [ 1  5 -1]]
Определитель:  -103
Неизвестная переменная:  1.0
Матрица A при замене 3го столбца на свободные члены: 
[[ 3  2  4]
 [ 2 -1 23]
 [ 1  7  5]]
Определитель:  -412
Неизвестная переменная:  4.0
_______________________
Ответ:  [2.0, 1.0, 4.0]
